export { default as SideBar } from './SideBar'
export { default as BreadCrumbs } from './BreadCrumbs'
export { default as TagList } from './TagList'
// export { default as Settings } from './Settings'
// export { default as TagsView } from './TagsView/index.vue'
